version: '3.8'

volumes:
  task_data:
  task_static:
  task_media:

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - task_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    env_file: .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./app:/app/app
  gateway:
    build: ./nginx
    env_file: .env
    depends_on:
      - app
    volumes:
      - task_media:/app/media
      - task_static:/staticfiles
    ports:
      - 80:80
