"""empty message

Revision ID: 79036fdb52ff
Revises: 
Create Date: 2025-08-30 16:27:41.312309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79036fdb52ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Дата обновления'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Название задачи'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание задачи'),
    sa.Column('status', sa.String(length=20), server_default='Создано', nullable=False, comment='Статус выполнения задачи'),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.CheckConstraint("status IN ('Создано', 'В работе', 'Завершено')", name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
