"""empty message

Revision ID: d4192378e5e2
Revises: 
Create Date: 2025-08-24 22:01:35.156002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4192378e5e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Дата обновления'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Название задачи'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробное описание задачи'),
    sa.Column('status', sa.String(length=20), server_default='Создано', nullable=False, comment='Статус выполнения задачи'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('Создано', 'В работе', 'Завершено')", name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
